### ISSUE TITLE
Make this a command

### ISSUE THREAD

**Issue by nathanael-h** [pojntfx/nextcloud-talk-jitsi-bot#1]
Hello, I just tried your chat bot and it runs as expected. 👍 
I wonder if it could be turned into a "command" as explained here : https://nextcloud-talk.readthedocs.io/en/latest/commands/ in Nextcloud docs ? 

Doing so would permit to invoke the command /videochat (for example) without having to add jitsi-bot user to the conversation. 

What do you think about this ?

**Comment by pojntfx** [comment]
@nathanael-h First of all, thanks for using the bot!

Sadly, this would have to be added from the command line:

"For security reasons commands can only be added via the command line. ./occ  talk:command:add --help gives you a short overview of the required arguments, but they are explained here in more depth." (from the link you've provided above).

This is a _very_ "retro" way to modify a server/install "extensions" and completely incompatible with any modern setup (like Docker, where containers are ephermal); I'd be more than happy to add a command if another way of adding commands were implemented by Nextcloud.

**Comment by pojntfx** [comment]
TBH it feels like Nextcloud Talk is really lacking when it comes to these kinds of features; chatbots should have first class support.

**Comment by pojntfx** [comment]
With that being said - #3 has been a rewrite in Go, so the actual bot is now a single binary that could be adapted to be a command pretty easily; while I lack the time rn, if someone could take a look at the `CreateChat` func it should be pretty easy to do now.

**Comment by nathanael-h** [comment]
Hello, 
I understand your concern about installation and deployment methods. On our side we deploy in the old fashion way 😉  so it is not a problem for us to type one more command when we install a server. Moreover I find that on user side, it is not very practical to have to add jitsi-bot to the conversation. 

I'll look if I can help you, with go written stuff... 

Thanks for your reply !

**Comment by sunjam** [comment]
> TBH it feels like Nextcloud Talk is really lacking when it comes to these kinds of features; chatbots should have first class support.

Sounds like someone might want to [open an issue](https://github.com/nextcloud/spreed) on the Nextcloud Talk github page. ;)

![](https://github.githubassets.com/images/icons/emoji/unicode/1f609.png)

**Comment by pojntfx** [comment]
@sunjam Your right, sorry for the rant, I've added an issue and proposal over in the repo: https://github.com/nextcloud/spreed/issues/3259

**Comment by pojntfx** [comment]
@nathanael-h Sure, I understand that - it just feels so backwards to add bots from the terminal when we have apps as well as an app distribution mechanism. I'd really appreciate your help with this though!

**Comment by pojntfx** [comment]
@nathanael-h In case you're still interested in making this particular bot a command, please take a look at https://github.com/pojntfx/nextcloud-talk-bot-jitsi - this has been turned into a generic framework for Nextcloud Talk chatbots over gRPC.
