### ISSUE TITLE
Jitsi Bot funktioniert nur ein paar Stunden

### ISSUE THREAD

**Issue by volkpa99** [pojntfx/nextcloud-talk-jitsi-bot#8]
Hallo,
ich habe den Jitsi Bot für meine Nextcloud eingerichtet und funktioniert soweit auch.
Leider funktioniert es bei mir aber nur wenige Stunden. Ein neustarten der Docker Container behebt das Problem und der Bot antwortet wieder auf #videochat etc.

In den Logs sieht man, dass der Bot regelmäßig crashed und "unexpected end of JSON input" wirft einen Error.

Habt ihr eine Idee, dass dieses Fehlerbild behebt?

Anbei die Logs:
`{"level":30,"time":1588771142875,"pid":27,"hostname":"a5ee28939ce3","msg":"connecting to nxta                                                                                                lkproxyd with address nxtalkproxyd:1969"}
{"level":30,"time":1588771142878,"pid":27,"hostname":"a5ee28939ce3","msg":"bot crashed, resta                                                                                                rting in 0.125 seconds:"}
{"level":30,"time":1588771142880,"pid":27,"hostname":"a5ee28939ce3","msg":"starting WebRTC no                                                                                                de subsystem with timeout 20 seconds"}
{"level":30,"time":1588771143085,"pid":27,"hostname":"a5ee28939ce3","msg":"connecting to nxta                                                                                                lkproxyd with address nxtalkproxyd:1969"}
{"level":30,"time":1588771143088,"pid":27,"hostname":"a5ee28939ce3","msg":"bot crashed, resta                                                                                                rting in 0.125 seconds:"}
{"level":30,"time":1588771143090,"pid":27,"hostname":"a5ee28939ce3","msg":"starting WebRTC no                                                                                                de subsystem with timeout 20 seconds"}
{"level":30,"time":1588771143319,"pid":27,"hostname":"a5ee28939ce3","msg":"connecting to nxta                                                                                                lkproxyd with address nxtalkproxyd:1969"}
{"level":30,"time":1588771143323,"pid":27,"hostname":"a5ee28939ce3","msg":"bot crashed, resta                                                                                                rting in 0.125 seconds:"}
{"level":30,"time":1588771143325,"pid":27,"hostname":"a5ee28939ce3","msg":"starting WebRTC no                                                                                                de subsystem with timeout 20 seconds"}
{"level":30,"time":1588771143581,"pid":27,"hostname":"a5ee28939ce3","msg":"connecting to nxta                                                                                                lkproxyd with address nxtalkproxyd:1969"}
{"level":30,"time":1588771143585,"pid":27,"hostname":"a5ee28939ce3","msg":"bot crashed, resta                                                                                                rting in 0.125 seconds:"}
{"level":30,"time":1588771143586,"pid":27,"hostname":"a5ee28939ce3","msg":"starting WebRTC no                                                                                                de subsystem with timeout 20 seconds"}
{"level":30,"time":1588771143795,"pid":27,"hostname":"a5ee28939ce3","msg":"connecting to nxta                                                                                                lkproxyd with address nxtalkproxyd:1969"}
{"level":30,"time":1588771143798,"pid":27,"hostname":"a5ee28939ce3","msg":"bot crashed, resta  `

`{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","error":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"could not read rooms, retrying"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","error":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"could not read rooms, retrying"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","error":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"could not read rooms, retrying"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","error":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"could not read rooms, retrying"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
{"level":"info","status":"unexpected end of JSON input","timestamp":"2020-05-06T13:16:52Z","message":"received Nextcloud client status"}
`

**Comment by pojntfx** [comment]
@volkpa99 I've just pushed 27ada8c08d01c41ea9c9ed3c24e554000a3a1f33 - I'm currently a bit tight on time, would you mind testing it? I've already pushed the Docker image, running `docker pull pojntfx/nxtalkproxyd` and then re-creating the containers (not restarting, but deleting & re-creating them) should be enough.

**Comment by pojntfx** [comment]
Issue appears to have been resolved; verified in long-term personal testing.
